/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx, js, jsx}",
    "./components/**/*.{ts,tsx, js, jsx}",
    "./app/**/*.{ts,tsx, js, jsx}",
    "./src/**/*.{ts,tsx, js, jsx}",
  ],
  theme: {
    fontFamily: {
      sans: [
        "var(--font-noto-serif-bengali)",
        "system-ui",
        "-apple-system",
        "sans-serif",
      ],
    },
    container: {
      center: "true",
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      screens: {
        xm: "500px",
      },
      fontFamily: {
        primary: ["var(--font-noto-serif-bengali)", "sans-serif"],
        secondary: ["var(--font-inter)", "sans-serif"],
        ternary: ["var(--plus-jakarta-sans)", "sans-serif"],
      },
      colors: {
        "ctm-orange": "rgba(var(--orange))",
        "ctm-blue": "rgba(var(--blue))",
        "ctm-green": "rgba(var(--green))",
        "ctm-purple": "rgba(var(--purple))",
        "card-highlighted": "#FF6709",
        "card-black-text": "#010F0E",
        "sidebar-highlight": "#F3F9F9",
        brand: "#0D9488",
        "brand-light": "#C2E4E1",
        "brand-accent": "#F3F9F9",
        "brand-accent-deep": "#E7F4F3",
        "brand-primary-light": "#E7F5F4",
        "brand-primary-lighter": "#F6FDFD",
        "secondary-brand-accent-light": "#F8F4E1",
        "secondary-brand-accent-lighter": "#FDFCF6",
        "green-deep-light": "#E6F4E8",
        "green-light": "#F6FDF7",
        // shadcn colors
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        primary: {
          // custom colors
          brand: "rgba(var(--primary-500))",
          50: "rgba(var(--primary-50))",
          100: "rgba(var(--primary-100))",
          300: "rgba(var(--primary-300))",
          500: "rgba(var(--primary-500))",
          700: "rgba(var(--primary-700))",
          900: "rgba(var(--primary-900))",
          // shadcn colors
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          // custom colors
          brand: "rgba(var(--secondary-500))",
          button: "#F9851A",
          50: "rgba(var(--secondary-50))",
          100: "rgba(var(--secondary-100))",
          300: "rgba(var(--secondary-300))",
          500: "rgba(var(--secondary-500))",
          700: "rgba(var(--secondary-700))",
          900: "rgba(var(--secondary-900))",
          // shadcn colors
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        tertiary: {
          DEFAULT: "#14b89b",
          foreground: "#ffffff",
          50: "#f0fdf9",
          100: "#ccfbee",
          200: "#99f6de",
          300: "#5eeacb",
          400: "#2dd4b4",
          500: "#14b89b",
          600: "#0d947f",
          700: "#0f7667",
          800: "#115e54",
          900: "#134e46",
          950: "#032421",
        },
        fontcolor: {
          DEFAULT: "rgba(var(--text-black))",
          title: "rgba(var(--text-black))",
          paragraph: "rgba(var(--text-paragraph))",
          description: "rgba(var(--text-description))",
          additional: "rgba(var(--text-additional))",
          disable: "rgba(var(--text-disable))",
          gray: "#828E9F",
          subtitle: "#414B4A",
        },
        greyscale: {
          0: "rgba(var(--greyscale-0))",
          50: "rgba(var(--greyscale-50))",
          100: "rgba(var(--greyscale-100))",
          200: "rgba(var(--greyscale-200))",
          300: "rgba(var(--greyscale-300))",
          400: "rgba(var(--greyscale-400))",
          500: "rgba(var(--greyscale-500))",
          600: "rgba(var(--greyscale-600))",
          700: "rgba(var(--greyscale-700))",
          800: "rgba(var(--greyscale-800))",
          900: "rgba(var(--greyscale-900))",
        },
        success: {
          DEFAULT: "rgba(var(--success-500))",
          50: "rgba(var(--success-50))",
          100: "rgba(var(--success-100))",
          300: "rgba(var(--success-300))",
          500: "rgba(var(--success-500))",
          700: "rgba(var(--success-700))",
          900: "rgba(var(--success-900))",
        },
        warning: {
          DEFAULT: "rgba(var(--warning-500))",
          50: "rgba(var(--warning-50))",
          100: "rgba(var(--warning-100))",
          300: "rgba(var(--warning-300))",
          500: "rgba(var(--warning-500))",
          700: "rgba(var(--warning-700))",
          900: "rgba(var(--warning-900))",
        },
        info: {
          DEFAULT: "rgba(var(--info-500))",
          50: "rgba(var(--info-50))",
          100: "rgba(var(--info-100))",
          300: "rgba(var(--info-300))",
          500: "rgba(var(--info-500))",
          700: "rgba(var(--info-700))",
          900: "rgba(var(--info-900))",
        },
        error: {
          DEFAULT: "rgba(var(--error-500))",
          50: "rgba(var(--error-50))",
          100: "rgba(var(--error-100))",
          300: "rgba(var(--error-300))",
          500: "rgba(var(--error-500))",
          700: "rgba(var(--error-700))",
          900: "rgba(var(--error-900))",
        },
        status: {
          gray: "rgba(var(--status-gray))",
          red: "rgba(var(--status-red))",
          black: "rgba(var(--status-black))",
          purple: "rgba(var(--status-purple))",
          cyan: "rgba(var(--status-cyan))",
          pink: "rgba(var(--status-pink))",
          green: "rgba(var(--status-green))",
          blue: "rgba(var(--status-blue))",
          orange: "rgba(var(--status-orange))",
        },
        gradientTeal: {
          start: "rgba(var(--gradient-teal-start))",
          end: "rgba(var(--gradient-teal-end))",
          hoverStart: "rgba(var(--gradient-teal-hover-start))",
          hoverEnd: "rgba(var(--gradient-teal-hover-end))",
        },
        background: {
          DEFAULT: "hsl(var(--background))", // shadcn default color
          // custom colors
          gray: "rgba(var(--bg-gray))",
          "primary-dark": "rgba(var(--bg-primary-dark))",
          "primary-darker": "rgba(var(--bg-primary-darker))",
        },
        // shadcn styles starts
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      backgroundImage: {
        "subscription-card-border": "var(--Gradient-Premium)",
        "discount-banner": "var(--Discount-Banner)",
        "subscribe-button-gradient": "var(--Gradient-Premium)",
        "subscribe-button-gradient-hover": "var(--Subscribe-Button-Hover)",
        "gradient-premium": "var(--Gradient-Premium)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        mid: "10px",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      boxShadow: {
        custom: "0px 4px 12px 0px #010F0E14",
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/aspect-ratio"),
    require("@tailwindcss/typography"),
  ],
};
